name: pblog deployment pipeline
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pblog static html
        uses: appleboy/ssh-action@0.1.2
        env:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
        with:
          scripts: |
            touch someFile.txt
            echo "The pipeline execution is complete"


